/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-container-low':     '#121c27',
        'surface-container-lowest':  '#050f19',
        'surface-container':         '#17202b',
        'surface-container-high':    '#212b35',
        'surface-container-highest': '#2c3641',
        'surface':                   '#0a141e',
        'surface-dim':               '#0a141e',
        'surface-bright':            '#303a45',
        'surface-variant':           '#2c3641',
        'background':                '#0a141e',
        'on-background':             '#d9e3f2',
        'on-surface':                '#d9e3f2',
        'on-surface-variant':        '#c2c7cf',
        'inverse-surface':           '#d9e3f2',
        'inverse-on-surface':        '#27313c',
        'outline':                   '#8c9199',
        'outline-variant':           '#42474e',
        'primary':                   '#9dcbfc',
        'primary-container':         '#2e5f8a',
        'primary-fixed':             '#cfe5ff',
        'primary-fixed-dim':         '#9dcbfc',
        'on-primary':                '#003355',
        'on-primary-container':      '#b5d8ff',
        'on-primary-fixed':          '#001d34',
        'on-primary-fixed-variant':  '#124a74',
        'inverse-primary':           '#31628d',
        'surface-tint':              '#9dcbfc',
        'secondary':                 '#a3cbef',
        'secondary-container':       '#204a69',
        'secondary-fixed':           '#cce5ff',
        'secondary-fixed-dim':       '#a3cbef',
        'on-secondary':              '#003351',
        'on-secondary-container':    '#92b9dd',
        'on-secondary-fixed':        '#001e31',
        'on-secondary-fixed-variant':'#204a69',
        'tertiary':                  '#d5bbfd',
        'tertiary-container':        '#67518b',
        'tertiary-fixed':            '#ecdcff',
        'tertiary-fixed-dim':        '#d5bbfd',
        'on-tertiary':               '#3a255c',
        'on-tertiary-container':     '#e1cbff',
        'on-tertiary-fixed':         '#240e46',
        'on-tertiary-fixed-variant': '#513c74',
        'error':                     '#ffb4ab',
        'error-container':           '#93000a',
        'on-error':                  '#690005',
        'on-error-container':        '#ffdad6',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body:     ['Inter', 'sans-serif'],
        label:    ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg:      '0.5rem',
        xl:      '0.75rem',
        '2xl':   '1rem',
        full:    '9999px',
      },
    },
  },
  plugins: [],
}
